name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, addons ]
  pull_request:
    branches: [ main, master, addons ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MAVEN_OPTS: '-Xmx1024m'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven Wrapper
        id: build
        run: |
          ./mvnw -B clean package
          if [ -d "target" ]; then echo "target_exists=true" >> $GITHUB_OUTPUT; else echo "target_exists=false" >> $GITHUB_OUTPUT; fi

      - name: Debug target directory
        run: ls -lR target || echo "No target directory"

      - name: Upload build artifact
        if: steps.build.outputs.target_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/

      - name: Run unit tests
        run: ./mvnw test -Dsurefire.reportFormat=plain

      - name: Run integration tests
        run: ./mvnw verify -Dsurefire.reportFormat=plain

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vishnuganesh/ridehailing:latest

      - name: Logout from Docker Hub
        run: docker logout
