name: Minimal Test

on:
  push:
    branches: [ addons ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo test
        run: echo "Hello, world!"
